# Generated by Django 3.2.2 on 2021-05-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='category',
            field=models.CharField(choices=[('essay', 'Essay'), ('ec', 'Extra Credit'), ('test', 'Test'), ('quiz', 'Quiz'), ('hwk', 'Homework'), ('ps', 'Problem Set')], max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(choices=[('math', 'MATH'), ('english', 'ENGLISH')], max_length=20),
        ),
    ]
